const equipments = {
  treadmill: {},
  dumbbell: {},
  barbell: {},
  kettlebell: {},
  bench: {},
  "squat rack": {},
  "pull-up bar": {},
  "lat pulldown": {},
  "leg press": {},
  rower: {},
  cable: {},
  smith: {},
  bike: {},
  elliptical: {},
  "ab roller": {},
  bands: {},
  "medicine ball": {},
  mat: {},
  "punching bag": {},
  ropes: {},
  "leg curl": {},
  "leg extension": {},
  "chest fly": {},
  hyperextension: {},
  hack: {},
  calf: {},
  "pec deck": {},
  dip: {},
  "tricep pushdown": {},
  preacher: {},
  ghd: {},
  sled: {},
};

export default equipments;
